import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Ubuntu } from "next/font/google";
import Providers from "../../Provider";
import GlobalLoader from "./Components/GlobalLoader";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "DigiMenu- Your Digital Menu Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className=' bg-gradient-to-br from-gray-50 to-white {ubuntu.className}'>
          <Providers>
          {children}
           <GlobalLoader />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
