import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Ubuntu } from "next/font/google";
import Providers from "../../Provider";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata = {
  title: "DIGIMENU",
  description: "Generated by create next app",
   icons: {
    icon: '../../public/2.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className=' bg-gradient-to-br from-gray-50 to-white {ubuntu.className}'>
          <Providers>
          <Navbar />
          {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
